### ISSUE TITLE
Kotlin应该怎么调用？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [FlyJingFish/OpenImage#10]

**Comment by SaltedFish-Extreme** [comment]
![image](https://github.com/FlyJingFish/OpenImage/assets/54784104/7384d5a0-4cf0-49f1-9653-0c894782dcd9)

哦，好像转换过来了，我再试试😂

**Comment by FlyJingFish** [comment]
这种问题就不要问了，大哥，你这问题与库无关，再有这种问题就直接关闭了

**Comment by FlyJingFish** [comment]
基础要靠自己

**Comment by SaltedFish-Extreme** [comment]
好吧，不好意思，没有kotlin的例子写法，我一下子也没看明白😂
