### ISSUE TITLE
imageViews.clear出现java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by hujiejeff** [FlyJingFish/OpenImage#11]
https://github.com/FlyJingFish/OpenImage/blob/dbd83b16e6f69a86eaf67e6381eb27df453967fc/OpenImageLib/src/main/java/com/flyjingfish/openimagelib/OpenImage.java#L232C14-L232C14

建议不要传递list引用，如果传递的是Array.asList，release会触发异常
![image](https://github.com/FlyJingFish/OpenImage/assets/22571708/8ad82804-25b4-4829-8e44-8fae156c79e1)

**Comment by FlyJingFish** [comment]
[最新版本2.0.5已修复此Bug](https://github.com/FlyJingFish/OpenImage/releases/tag/v2.0.5)

支持传入 `Array.asList`
