### ISSUE TITLE
和Fragment一起使用会有内存泄漏问题

### ISSUE THREAD

**Issue by whitestarlau** [FlyJingFish/OpenImage#12]
目前我们的应用是单Activity框架，使用navigation来进行导航。Fragment在onDestroyView之后需要销毁界面，但是这个库持有了recyclerView，不让销毁。跟进源码看了一下，库里面注册了acitivity的LifecycleEventObserver，在activity销毁的时候才会释放持有的资源。能否适配Fragment的生命周期？或者提供手动注销释放的办法。

**截图**
![微信图片_20230712114612](https://github.com/FlyJingFish/OpenImage/assets/9989324/abc1ad20-3502-4042-a872-89c345b5c032)

**设备信息:**
 - 手机型号: [e.g. 小米]
 - Android 12
 - OpenImageGlideLib:2.0.1

**Comment by FlyJingFish** [comment]
哦～稍后会修复上述问题，功能上线后，会同步到这里

**Comment by FlyJingFish** [comment]
[最新版本2.0.9已修复此Bug](https://github.com/FlyJingFish/OpenImage/releases/tag/v2.0.9)
