### ISSUE TITLE
左右滑动过于敏感

### ISSUE THREAD

**Issue by Jason-wam** [FlyJingFish/OpenImage#13]
**详细说明功能**
左右滑动过于敏感，缩放图片会导致图片左右滑动误触，能否修改滑动阻尼

**截图说明**
添加截图最好是 gif 或 视频

**Comment by FlyJingFish** [comment]
[最新版 2.1.1 已处理](https://github.com/FlyJingFish/OpenImage/releases/tag/v2.1.1)

**Comment by JuanbingTeam** [comment]
貌似没有很好的解决呢？ 是不是双指触动的时候就直接不要滑动只触发缩放。

**Comment by FlyJingFish** [comment]
上次更新主要针对双指不会触发切换图片。目前的问题是双指转一指，有可能导致切换，因为我们无法保证双指同时离开屏幕。这两天会再更新一版，双指触摸转一指也不会切换的（因为中心仓库那边貌似出bug了导致新版本发布不了）。

**Comment by JuanbingTeam** [comment]
暂时继承了StandardOpenImageActivity, 在activity的dispatchTouchEvent里做了下处理。 
检测到双指就禁用了ViewPager2的侧滑。

**Comment by FlyJingFish** [comment]
嗯。你这个方案也不错。你可以试下[最新版2.1.2](https://github.com/FlyJingFish/OpenImage/releases/tag/v2.1.2)，是否跟你这么改一样的效果

**Comment by FlyJingFish** [comment]
嗯，你这个方法也不错，你可以试试[最新版2.1.3](https://github.com/FlyJingFish/OpenImage/releases/tag/v2.1.3)
