### ISSUE TITLE
优先加载缩略图

### ISSUE THREAD

**Issue by appdev** [FlyJingFish/OpenImage#14]
**详细说明功能**

同时存在缩略图与大图在图片浏览的时候应该挺普遍的，希望能在缩略图存在的时候，优先加载缩略图，然后加载大图。

**Comment by FlyJingFish** [comment]
你是指切换图片时先加载缩略图再加载大图吗

**Comment by appdev** [comment]
是的

**Comment by FlyJingFish** [comment]
你的意见已采纳，详细可看[新版本 2.1.4更新说明](https://github.com/FlyJingFish/OpenImage/releases/tag/v2.1.4)

**Comment by appdev** [comment]
谢谢大佬O.O
