### ISSUE TITLE
双指放大，放大后的图片旋转

### ISSUE THREAD

**Issue by LazyIonEs** [FlyJingFish/OpenImage#15]
**描述一下大概怎么回事**
双指放大，放大后的图片旋转
Gif压的有点模糊

**如何复现**
使用CameraX拍照后的照片，正常点击浏览正常，双指放大后图片旋转

**错误日志**
把错误日志贴出来

**截图说明**
![屏幕录制2023-09-15 11 14 48](https://github.com/FlyJingFish/OpenImage/assets/86482436/b30aa8a6-acf8-400b-8880-691417a08604)

**设备信息:**
 - 手机型号: RMX3370
 - Android版本 Android 13
 - 使用的哪个库及其版本 OpenImageFullLib:2.1.4

**Comment by appdev** [comment]
`PhotoViewAttacher`类 这个方法注释掉下面的代码就好了。

```java
    private void setImageViewMatrix(Matrix matrix) {
        mImageView.setImageMatrix(matrix);
        // Call MatrixChangedListener if needed
//        if (mMatrixChangeListener != null) {
//            RectF displayRect = getDisplayRect(matrix);
//            if (displayRect != null) {
//                mMatrixChangeListener.onMatrixChanged(displayRect);
//            }
//        }
    }
```

**Comment by FlyJingFish** [comment]
Bug已修复 [新版本 2.1.5更新说明](https://github.com/FlyJingFish/OpenImage/releases/tag/v2.1.5)

**Comment by FlyJingFish** [comment]
> `PhotoViewAttacher`类 这个方法注释掉下面的代码就好了。
> 
> ```java
>     private void setImageViewMatrix(Matrix matrix) {
>         mImageView.setImageMatrix(matrix);
>         // Call MatrixChangedListener if needed
> //        if (mMatrixChangeListener != null) {
> //            RectF displayRect = getDisplayRect(matrix);
> //            if (displayRect != null) {
> //                mMatrixChangeListener.onMatrixChanged(displayRect);
> //            }
> //        }
>     }
> ```

这样会丧失查看超大图的能力，2.1.5已修复可以尝试下
