### ISSUE TITLE
addMoreView 没有移除，添加两次会崩溃

### ISSUE THREAD

**Issue by 18810979455** [FlyJingFish/OpenImage#16]
**描述一下大概怎么回事**
例如使用什么功能时会这样
addMoreView 没有移除，添加两次会崩溃

**如何复现**
把复现步骤详细说明说下

OpenImage.with(activity).apply {
            setNoneClickView()
            setImageUrl(filePath, MediaType.IMAGE)
            if (openImageView!=null){
                val layoutParams = FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT, 200.pt)
                addMoreView(openImageView, layoutParams, MoreViewShowType.IMAGE,true)
            }
            show()
        }

**错误日志**
把错误日志贴出来

**截图说明**
添加截图最好是 gif 或 视频

**设备信息:**
 - 手机型号: [e.g. 小米]
 - Android版本 [e.g. Android 12]
 - 使用的哪个库及其版本 [e.g. OpenImageGlideLib:1.8.8]

**Comment by FlyJingFish** [comment]
同一个View你加了两次吗
