### ISSUE TITLE
还是有内存泄露

### ISSUE THREAD

**Issue by haiTangKnight** [FlyJingFish/OpenImage#18]
GC Root: Globalvariable in native code
android.os.ResultReceiver$MyResultReceiverinstanceLeaking: UNKNOWNRetaining 59.3 kB in 929 objectsResultReceiver$MyResultReceiver.this$o
android.app.ExitTransitionCoordinatorinstanceLeaking: UNKNOWNRetaining 58.8 kB in 928 objectsActivityTransitionCoordinator.mResultReceiver
android.app.EnterTransitionCoordinator
instance
Leaking:UNKNOWNRetaining 58.5 kB in 918 objectsEnterTransitionCoordinator.mviewsReadyListener
com.android.internal.view.OneShotPreDrawListenerinstanceLeaking: UNKNOWNRetaining 58.2 kB in 909 objectsOneShotPreDrawListener.mview
com.android.internal.policy.DecorViewinstanceLeaking:YES(View.mContextreferences a destroyed activity)Retaining 58.0 kB in 900 objectsView not part of a window viewhierarchyView.mAttachlnfo is null (viewdetached)View.mWindowAttachCount = 0mContext instance of com.android.internal.policy.DecorContext, wrappingactivity com.flyjingfish.openimagelib.FixAndroid12BugActivity withmDestroyed = trueDecorView.mContentRoot
android.widget.LinearLayout instanceLeaking: YES(DecorView个 is leakingand View.mContext references adestroyed activity)Retaining 2.2 kB in 25 objectsView is part of a window viewhierarchy
View.mAttachInfo is null (viewdetached)View.mWindowAttachCount =0mContextinstance of comflviinafishopenimagelib.FixAndroid12BugActivitywith mDestroyed = trueView.mContext
com.flyjingfish.openimagelib.FixAndroid12BugActivityinstanceLeaking: YES

**Comment by FlyJingFish** [comment]
这个不用管， [可以看下这里](https://github.com/FlyJingFish/OpenImage/issues/8)
