### ISSUE TITLE
PhotoViewAttacher 一处逻辑判断产生的问题

### ISSUE THREAD

**Issue by appdev** [FlyJingFish/OpenImage#19]
**描述一下大概怎么回事**

在 PhotoViewAttacher  https://github.com/FlyJingFish/OpenImage/blob/091015ec414d02f275a6701b21ce0211869de9d8/OpenImageLib/src/main/java/com/flyjingfish/openimagelib/photoview/PhotoViewAttacher.java#L1051C15-L1051C15

` float scaleStartViewHW = mStartHeight /  ; ` 

如果我的 StartHeight 或者 StartWidth 不传，就会让长图默认缩放到很小。

----
比较好奇为什么这里要用 mStartHeight mStartWidth 来做比较。这里的大图判断跟初始大小似乎没有关系

**Comment by FlyJingFish** [comment]
你是碰到什么bug了吗
