### ISSUE TITLE
关于查看大图后父Activity的返回动画被修改的问题

### ISSUE THREAD

**Issue by SageMik** [FlyJingFish/OpenImage#2]
如gif图所示，当我从首页进入到RecyclerView的Activity再返回时，返回动画是正常的从左到右退出；
但当我查看大图之后，RecyclerView的Activity的返回动画就变成了淡出退出了，我实际应用到项目里也有这个问题。
我希望父Activity保留原来的返回动画，所以不知道大佬是否有解决方案，或者可以修复一下这个问题？

![Screenrecorder-2023- -big-original](https://user-images.githubusercontent.com/73378246/232276790-f833b053-77e6-4c12-b1f5-32679290fe55.gif)

**Comment by FlyJingFish** [comment]
现在没有更好的办法，不过你可以在调用打开大图的所在Activity中重写 onBackPressed 方法，解决此问题。
例如：
    @Override
    public void onBackPressed() {
        finish();
    }
因为此问题只在Android 12以上才会出现，如果你不想影响太多设备，可按如下写法来写
    @Override
    public void onBackPressed() {
        if (Build.VERSION.SDK_INT > Build.VERSION_CODES.R) {
            finish();
        }else {
            super.onBackPressed();
        }
    }

**Comment by FlyJingFish** [comment]
目前升级最新版本1.7.2版本可解决此问题，不用重写 onBackPressed 了
