### ISSUE TITLE
RecyclerView的动画问题

### ISSUE THREAD

**Issue by Blacknetbar** [FlyJingFish/OpenImage#20]
当我的recyclerView是一个反序列表的时候，退出查看大图模式后的动画，返回到的图片在列表中的位置是错误的

**Comment by FlyJingFish** [comment]
你是怎么反序的，下边这样的？
```java
new LinearLayoutManager(this,LinearLayoutManager.VERTICAL,true)
```

**Comment by Blacknetbar** [comment]
是的

**Comment by FlyJingFish** [comment]
如果仅仅是这样，显示没问题，你有没有把传进来的数据又改了顺序

**Comment by Blacknetbar** [comment]
传进来的数据是一个url，我是继承了一个OpenImageActivity去写的页面，图片或视频的数据用的addFrontData和addData方法

**Comment by FlyJingFish** [comment]
你是把两个方法用反了吧，RecyclerView 设置 reverse 为true之后，虽然显示是倒着的，但是数据顺序还是正着的。所以你这种情况，在更新数据时
1、如果在大图页面用了addData 上一页面的RecyclerView的数据就得往后加，前一页面看起来就是列表**下边**加了数据
2、如果是 addFrontData的数据就是往前加，前一页面看起来就是列表**上边**加了数据
