### ISSUE TITLE
是否可以增加类似小红书的双指放大过渡到大图模式呢?

### ISSUE THREAD

**Issue by Ryokooo** [FlyJingFish/OpenImage#22]
**详细说明功能**
详细说明功能是怎么回事

**截图说明**
添加截图最好是 gif 或 视频

**Comment by FlyJingFish** [comment]
小红书详情页面图片区域高度有最高限制，显示模式为fitCenter，放大图片时应该是在详情页面完成的过渡，松手后可以看出来基本上是没有打开新的大图页面，应该还是在详情页面对PhotoView做了一定的缩放位移，这应该不属于本库的职责范围了，你可以借助本库中的PhotoView来完成图片触摸功能，TouchCloseLayout来完成下拉关闭，中间的松手位移等功能可以借助MotionLayout来完成。
