### ISSUE TITLE
setNoneClickView 能增加过渡动画效果吗

### ISSUE THREAD

**Issue by byc4426** [FlyJingFish/OpenImage#23]
**详细说明功能**
setNoneClickView()  打开、关闭没有过渡动画效果,
能增加过渡效果吗，比如直接从 屏幕中间、左上角等位置 缩放到全屏

**Comment by FlyJingFish** [comment]
[可以使用这块的setOpenImageActivityCls](https://github.com/FlyJingFish/OpenImage/wiki#%E5%9C%A8%E8%BF%99%E4%BB%8B%E7%BB%8D%E4%B8%8Bopenimageactivity%E5%AE%83%E9%87%8C%E8%BE%B9%E5%86%85%E7%BD%AE%E4%BA%86%E4%B8%80%E4%BA%9B%E6%96%B9%E6%B3%95%E6%82%A8%E5%BE%88%E5%8F%AF%E8%83%BD%E7%94%A8%E5%88%B0%E7%9B%AE%E5%89%8D%E6%9C%89)，自定义一个页面,给Activity设置style里边的动画即可
