### ISSUE TITLE
设置大图视频不旋转

### ISSUE THREAD

**Issue by LazyIonEs** [FlyJingFish/OpenImage#24]
**描述一下大概怎么回事**
设置大图视频不旋转，即隐藏全屏按钮，有对应的api吗，还是需要自己自定义实现

**Comment by FlyJingFish** [comment]
需要你自定义实现，[可参考这里](https://github.com/FlyJingFish/OpenImage/wiki#%E4%BA%8C%E5%A6%82%E6%9E%9C%E6%9C%89%E9%9C%80%E8%A6%81%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A7%86%E9%A2%91fragment%E9%A1%B5%E9%9D%A2%E8%AF%B7%E5%AE%9E%E7%8E%B0videofragmentcreate-%E5%B9%B6%E7%BB%A7%E6%89%BFbaseimagefragment%E6%88%96videoplayerfragment%E5%9C%A8openimagefulllib%E5%8C%85%E4%B8%8B%E5%90%A6%E5%88%99%E5%8A%A8%E7%94%BB%E6%95%88%E6%9E%9C%E5%8F%AF%E8%83%BD%E4%B8%8D%E5%A4%9F%E5%AE%8C%E5%96%84)的FriendsPlayerFragment，换掉播放器的UI，可直接将播放器布局中的全屏按钮删除即可
