### ISSUE TITLE
OpenImageUrl接口中的getImageUrl能否使用mipmap/drawable的图片

### ISSUE THREAD

**Issue by lsCoding666** [FlyJingFish/OpenImage#25]
OpenImageUrl接口中的getImageUrl能否使用mipmap/drawable的图片

**Comment by FlyJingFish** [comment]
你可以使用 assets 方式加载安装包里的图片，例如：
![image](https://github.com/FlyJingFish/OpenImage/assets/96164429/d642e3ed-a23c-473a-b7bf-18a667bf3675)

**Comment by lsCoding666** [comment]
对于mipmap 或者是 drawable的话 我试了下还能这样
![image](https://github.com/FlyJingFish/OpenImage/assets/73888354/b3e3b372-4fd2-4eed-ad1f-178cef0c840a)

**Comment by FlyJingFish** [comment]
可以的话就行
