### ISSUE TITLE
对于多ItemType的Rv，如果imageView的id不一样，会导致闪退

### ISSUE THREAD

**Issue by lsCoding666** [FlyJingFish/OpenImage#26]
如果有一个rv，有两种item，每种item下面都只有一个imageview，但是id不一样，一个id是A，一个是B。rv一共用4个item，也就是4张图片，A，b类型的各2张。
如果我点击A的时候，希望只显示A的两张，点b的时候也只显示b的两张，于是我这么写
```
     doorstepRvAdapter.setOnCustomItemClickListener(new DoorstepRvAdapter.OnItemClickListener() {
            @Override
            public void onTakePicClick() {
                Intent intent = new Intent(mContext, EventCaptureActivity.class);
                whichRv = 0;
                activityResultLauncher.launch(intent);
            }

            @Override
            public void onShowExampleClick() {
                OpenImage.with(mContext)
                        //点击ImageView所在的RecyclerView（也支持设置setClickViewPager2，setClickViewPager，setClickGridView，setClickListView，setClickImageView，setClickWebView，setNoneClickView）
                        .setClickRecyclerView(binding.rvShopDoorstepPhoto, new SourceImageViewIdGet() {
                            @Override
                            public int getImageViewId(OpenImageUrl data, int position) {
                                return R.id.ivExamplePic;//点击的ImageView的Id或者切换图片后对应的ImageView的Id
                            }
                        })
                        //点击的ImageView的ScaleType类型（如果设置不对，打开的动画效果将是错误的）
                        .setSrcImageViewScaleType(ImageView.ScaleType.CENTER_CROP, true)
                        //RecyclerView的数据
                        .setImageUrlList(doorstepRvAdapter.getData())
                        //点击的ImageView所在数据的位置
                        .setClickPosition(position)
                        //开始展示大图
                        .show();
            }

            @Override
            public void onUploadPicLongClick(int position) {
                doorstepRvAdapter.remove(position);
            }

            @Override
            public void onUploadPicClick(int position) {
                OpenImage.with(mContext)
                        //点击ImageView所在的RecyclerView（也支持设置setClickViewPager2，setClickViewPager，setClickGridView，setClickListView，setClickImageView，setClickWebView，setNoneClickView）
                        .setClickRecyclerView(binding.rvShopDoorstepPhoto, new SourceImageViewIdGet() {
                            @Override
                            public int getImageViewId(OpenImageUrl data, int position) {
                                return R.id.ivUploadPic;//点击的ImageView的Id或者切换图片后对应的ImageView的Id
                            }
                        })
                        //点击的ImageView的ScaleType类型（如果设置不对，打开的动画效果将是错误的）
                        .setSrcImageViewScaleType(ImageView.ScaleType.CENTER_CROP, true)
                        //RecyclerView的数据
                        .setImageUrlList(doorstepBeanList)
                        //点击的ImageView所在数据的位置
                        .setClickPosition(position)
                        //开始展示大图
                        .show();
            }
        });
```
imageview的id、position都对，但是点击Bitem时会报错，我排查后原因如下：
在OpenImage4ParseData.initShareView这个方法，有一段这样的代码，如果找不到image则直接返回null
![image](https://github.com/FlyJingFish/OpenImage/assets/73888354/827e97d6-5ecf-4941-bf39-b87026623445)
如果返回了null，则会直接抛出异常，app就会闪退。
我觉得这样写有点问题，如果找不到的话应该去下一个rv的item找，而不是直接返回null。这样在多itemType的RV工作会异常

**Comment by FlyJingFish** [comment]
![image](https://github.com/FlyJingFish/OpenImage/assets/96164429/7b214b05-481a-45ba-8f17-26b90dd9d285)
这块根据你的数据返回对应的id
另外，对于没有图片或视频的那个item的数据 type 返回 none，可以参考本项目聊天页面功能去写

**Comment by lsCoding666** [comment]
这里已经是根据数据返回id了，因为这里有自定义的点击事件，点击不同的item调用不同的方法，对于SHOW_EXAMPLE这种类型的item，就会调onShowExampleClick，所以这里id是对的，就是应该写死的。另外，没有图片的我返回了null
![image](https://github.com/FlyJingFish/OpenImage/assets/73888354/6c4fa0d6-d3eb-4eb8-b2bb-27dc0202538a)

如果说圈住的地方改成根据不同类型的itemType，返回对应的imageView的id的话，就会导致在查看大图的页面不能达到我想要的“如果我点击A类型的item的时候，希望只显示A的两张，点b的时候也只显示b的两张”这种效果，因为这样实际上是把所有类型的item的imageview 都设置成一样的效果是一样的。


> ![image](https://private-user-images.githubusercontent.com/96164429/301419197-7b214b05-481a-45ba-8f17-26b90dd9d285.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzI2MzIsIm5iZiI6MTcwNjc3MjMzMiwicGF0aCI6Ii85NjE2NDQyOS8zMDE0MTkxOTctN2IyMTRiMDUtNDgxYS00NWJhLThmMTctMjZiOTBkZDlkMjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDA3MjUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YzMzZDRmNGFkMjFkZDA3YTA2YjJlY2Q4ZWQzOTE3NWQxOTFiMzY2MDgyMzIzNDVmNzZhZjllZTBiMDkyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CI7EvOG9u7XlXYHCMp1huw9Efc6rKQfPw2sA0hGeYds) 这块根据你的数据返回对应的id 另外，对于没有图片或视频的那个item的数据 type 返回 none，可以参考本项目聊天页面功能去写

**Comment by FlyJingFish** [comment]
如果你想看整个List中的某种类型数据，那你就在getType处也修改下，针对A 类型的Item，返回的数据中，只有 A类型的getType返回MediaType.IMAGE或MediaType.VIDEO，其他的返回MediaType.NONE或null
