### ISSUE TITLE
是否支持设置图片的清晰度？显示的图片比实际模糊

### ISSUE THREAD

**Issue by kingdawin** [FlyJingFish/OpenImage#27]
问题描述:
打开图片查看，图片不清晰
                //在点击时调用（以下以RecyclerView为例介绍）
                OpenImage.with(MainActivity.this)
                        //打开大图页面时没有点击的ImageView则用这个
                        .setNoneClickView()
                        //图片的数据
                        .setImageUrlList(datas)
                        //默认展示数据的位置
                        .setClickPosition(datas.size()-1)
                        //开始展示大图
                        .show();

**设备信息:**
 - Android TV 测试机
 - Android版本 13
 - 库版本 OpenImageFullLib:2.2.1

**Comment by FlyJingFish** [comment]
[请仔细看这里](https://github.com/FlyJingFish/OpenImage?tab=readme-ov-file#b%E5%9C%A8%E6%82%A8%E7%9A%84%E6%95%B0%E6%8D%AE%E5%AE%9E%E4%BD%93%E7%B1%BB%E4%B8%8A%E5%AE%9E%E7%8E%B0openimageurl%E6%8E%A5%E5%8F%A3%E8%BF%99%E4%B8%AA%E6%96%B9%E5%BC%8F%E9%80%82%E5%90%88%E6%98%BE%E7%A4%BA%E5%9B%BE%E7%89%87%E5%92%8C%E8%A7%86%E9%A2%91%E7%9A%84%E6%B7%B7%E5%90%88%E6%95%B0%E6%8D%AE%E5%BB%BA%E8%AE%AE%E4%BD%BF%E7%94%A8%E8%BF%99%E4%B8%AA%E6%96%B9%E5%BC%8F)，不要急于去写代码
