### ISSUE TITLE
双指手势控制图片旋转

### ISSUE THREAD

**Issue by LankyBin** [FlyJingFish/OpenImage#28]
**详细说明功能**
双指放大缩小的基础上，判断手势扭转操作，实现图片的旋转，旋转方式以贴近90° 180° 270° 360°（回正）的形式自适应摆正

**截图说明**
添加截图最好是 gif 或 视频

**Comment by FlyJingFish** [comment]
这种需求我感觉不适用于大多数人，建议自行实现
