### ISSUE TITLE
点击的图像和最后展示的图像不一致

### ISSUE THREAD

**Issue by Jackieqfh143** [FlyJingFish/OpenImage#29]
private void onShowImage(Context context,
                             ViewHolder holder, ViewGroup recyclerView,
                             List<IconImage> iconImageList){
        int position = holder.getAdapterPosition();
        XLog.d( "current position is: " + position);
        List<ImageEntity> datas = new ArrayList<>();
        for (int i = 0; i < iconImageList.size(); i++){
            IconImage iconImage = iconImageList.get(i);
            String imgUrl = iconImage.getPath();
            String smallImgUrl = imgUrl.contains(".png") ? imgUrl.replace(".png", "_small.png") : imgUrl;
            ImageEntity imageEntity = new ImageEntity(imgUrl,smallImgUrl, 0);
            datas.add(imageEntity);
        }
        OpenImage.with(context)
                //点击ImageView所在的RecyclerView（也支持设置setClickViewPager2，setClickViewPager，setClickGridView，setClickListView，setClickImageView，setClickWebView）
                .setClickRecyclerView((RecyclerView) recyclerView,new SourceImageViewIdGet() {
                    @Override
                    public int getImageViewId(OpenImageUrl data, int position) {
                        return R.id.icon_image;//点击的ImageView的Id或者切换图片后对应的ImageView的Id
                    }
                })
                //点击的ImageView的ScaleType类型（如果设置不对，打开的动画效果将是错误的）
                .setSrcImageViewScaleType(ImageView.ScaleType.CENTER_CROP,true)
                //RecyclerView的数据
                .setImageUrlList(datas)
                //点击的ImageView所在数据的位置
                .setClickPosition(position)
                //设置加载失败时显示的图片（可不设置）
                .setErrorResId(R.mipmap.ic_launcher)
                //设置true后关闭时，将看不到前一页面正在查看的图片（可不设置）
                .setShowSrcImageView(true)
                //设置切换图片时前一页面跟随滚动（可不设置）
                //设置显示关闭按钮（可不设置，默认不显示，打开后默认只在显示图片时显示，因为视频页面默认有返回按钮，如需都要显示可在此基础上传入更多参数）
                .setShowClose()
                .setGalleryEffect(0)
                //设置切换图片监听（可不设置）
                .setOnSelectMediaListener(new OnSelectMediaListener() {
                    @Override
                    public void onSelect(OpenImageUrl openImageUrl, int position) {

                    }
                })
                //设置切换大图时的效果（可不设置，本库中目前只有这一个，如需其他效果可参照ScaleInTransformer自行定义效果）
                .addPageTransformer(new ScaleInTransformer())
                .show();
    }

我使用上述代码来调用OpenImage库展示图像，使用setClickPosition方法设置的图像下标position和最终展示的图像下标总是相差1，例如点击第3张图像（position = 2），最终却展示第4张图像（position = 3），另外，展示图像的时候这种卡在中间的效果怎么去掉？我只想展示所点击的图像。在这个例子中最奇怪的一点是，总共5张图像，不管我点击最后的三张图像中的哪一张，最后展示的都是如第2张图片所展示的结果，图像卡在第四张和第五张图像的中间
![微信图片_20240501151816](https://github.com/FlyJingFish/OpenImage/assets/49147103/49a35db2-cd44-437c-86ec-a77330e63fb4)
![微信图片_20240501151825](https://github.com/FlyJingFish/OpenImage/assets/49147103/d7840348-2ab3-48a5-978a-c740244daf62)

**Comment by FlyJingFish** [comment]
你在调用setGalleryEffect，不懂的功能不要乱加

**Comment by Jackieqfh143** [comment]
> 你在调用setGalleryEffect，不懂的功能不要乱加

之前把这个setGalleryEffect删掉了，结果还是一样的。我以为是要设成0才不会有gallery的效果

**Comment by FlyJingFish** [comment]
你自定义页面了吗

**Comment by FlyJingFish** [comment]
可不设置的都先去掉

**Comment by Jackieqfh143** [comment]
private void onShowImage(Context context,
                             ViewHolder holder, ViewGroup recyclerView,
                             List<IconImage> iconImageList){
        int position = holder.getAdapterPosition();
        List<ImageEntity> datas = new ArrayList<>();
        for (int i = 0; i < iconImageList.size(); i++){
            IconImage iconImage = iconImageList.get(i);
            String imgUrl = iconImage.getPath();
            String smallImgUrl = imgUrl.contains(".png") ? imgUrl.replace(".png", "_small.png") : imgUrl;
            ImageEntity imageEntity = new ImageEntity(imgUrl,smallImgUrl, 0);
            datas.add(imageEntity);
        }
        OpenImage.with(context)
                .setClickRecyclerView((RecyclerView) recyclerView,new SourceImageViewIdGet() {
                    @Override
                    public int getImageViewId(OpenImageUrl data, int position) {
                        return R.id.icon_image;//点击的ImageView的Id或者切换图片后对应的ImageView的Id
                    }
                })
                //点击的ImageView的ScaleType类型（如果设置不对，打开的动画效果将是错误的）
                .setSrcImageViewScaleType(ImageView.ScaleType.CENTER_CROP,true)
                //RecyclerView的数据
                .setImageUrlList(datas)
                //点击的ImageView所在数据的位置
                .setClickPosition(position)
                .show();
    }

能删的都删了，还是不行。因为我的诉求很简单，就是单纯查看图片，所以没有自定义页面。使用自定义页面的什么方法来修改所展示的页面？另外这个gallery效果是我的项目中不需要的，有什么设置能关闭它吗？

**Comment by FlyJingFish** [comment]
这个显示图片的就是个官方的ViewPager2，你能用出这种bug来，根本就想不到为什么，我还觉得奇怪呢

**Comment by FlyJingFish** [comment]
你用其他项目再次接入使用看看效果。或者开个demo。然后想想你用了那个屏幕适配方案，你的ViewPager2版本是不是有问题，或者换个手机试试，看看到底是哪里导致的

**Comment by Jackieqfh143** [comment]
好的，感谢

**Comment by FlyJingFish** [comment]
RecyclerView低版本的Bug，最新版2.2.3已解决
