### ISSUE TITLE
依然有java.lang.NullPointerException: Attempt to read from field 'ux0 qx0.a' on a null object reference

### ISSUE THREAD

**Issue by BugMonkey** [FlyJingFish/OpenImage#32]
**描述一下大概怎么回事**
已升到2.2.3，仍然有这个问题

**错误日志**
07-17 18:59:00.979 24043 24043 E DCrashHandler: theone 程序发生崩溃=============> 
07-17 18:59:00.979 24043 24043 E DCrashHandler: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.camera.zdazz/com.camera.zdazz.ui.photos.ImageActivity}: java.lang.NullPointerException: Attempt to read from field 'ux0 qx0.a' on a null object reference
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4841)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:5059)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:7282)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:7156)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:50)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:3131)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.os.Handler.dispatchMessage(Handler.java:117)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.os.Looper.loopOnce(Looper.java:205)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.os.Looper.loop(Looper.java:293)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.ActivityThread.loopProcess(ActivityThread.java:10062)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.ActivityThread.main(ActivityThread.java:10051)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at java.lang.reflect.Method.invoke(Native Method)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1245)
07-17 18:59:00.979 24043 24043 E DCrashHandler: Caused by: java.lang.NullPointerException: Attempt to read from field 'ux0 qx0.a' on a null object reference
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at x5.onCreate(BaseFragment.java:5)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at com.flyjingfish.openimagelib.BaseImageFragment.onCreate(Unknown Source:0)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:6)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:5)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:21)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:3)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:57)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:4)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at androidx.fragment.app.FragmentController.dispatchCreate(Unknown Source:4)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:3)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at com.flyjingfish.openimagelib.a.onCreate(BaseActivity.java:1)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at com.flyjingfish.openimagelib.OpenImageActivity.onCreate(OpenImageActivity.java:8)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at com.camera.zdazz.ui.photos.ImageActivity.onCreate(Native Method)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.Activity.performCreate(Activity.java:8582)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.Activity.performCreate(Activity.java:8555)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4809)
07-17 18:59:00.979 24043 24043 E DCrashHandler: 	... 16 more
07-17 18:59:01.003 24043  4737 E comSDKTheone-->: addParam oldRequest.body()---> okhttp3.FormBody@3620eb0
07-17 18:59:01.017 24043  4737 E Md5Utils--result--->: 0a1b674ff60a09472249a4876512de48
07-17 18:59:01.020 24043  4737 E Md5Utils--result--->: aece4eedf15719a9a372f6035a053042
07-17 18:59:01.985 24043 24043 E DEBUG   : encryptLog: false, zipCrashLog: false
07-17 18:59:01.985 24043 24043 E DEBUG   : begin to generate java report
[DEBUG] Read 137 lines, wrote 137 lines.
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
battery info:
level: 40
scale: 100
health: 2 (Good)
pluged: 0 (None)
status: 3 (Discharging)
voltage: 3821
temperature: 380
technology: Li-poly
battery low: false
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
disk info:
/data/data/com.camera.zdazz:
  total:      237666304 kB
  available:  121553652 kB
  free:       121553652 kB
  block size: 4096 B

/storage/emulated/0:
  total:      237666304 kB
  available:  121553652 kB
  free:       121553652 kB
  block size: 4096 B

--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
device status:
has root: false
build tags: release-keys
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
opened file count: 803, write limit: 900.
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
um_umid
07cd8fa85eb969312c877d0fae151845od
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
um_action_log
{"source":0,"action_name":"page_view","action_parameter":[{"name":"ui.photos.ImageActivity-1721213902858-onPaused"},{"name":"ui.photos.VideoActivity-1721213902880-onCreated"},{"name":"ui.photos.VideoActivity-1721213902927-onStarted"},{"name":"ui.photos.VideoActivity-1721213902930-onResumed"},{"name":"ui.photos.PhotoAlbumActivity-1721213903470-onStopped"},{"name":"ui.photos.ImageActivity-1721213903472-onStopped"},{"name":"ui.photos.VideoActivity-1721213910780-onPaused"},{"name":"ui.photos.VideoActivity-1721213911225-onStopped"},{"name":"ui.photos.VideoActivity-1721213926935-onStarted"},{"name":"ui.photos.VideoActivity-1721213926947-onResumed"},{"name":"ui.photos.VideoActivity-1721213936386-onPaused"},{"name":"ui.photos.PhotoAlbumActivity-1721213936400-onStarted"},{"name":"ui.photos.ImageActivity-1721213936402-onStarted"},{"name":"ui.photos.ImageActivity-1721213936404-onResumed"},{"name":"ui.photos.VideoActivity-1721213936971-onStopped"},{"name":"ui.photos.VideoActivity-1721213936972-onDestroyed"},{"name":"ui.photos.ImageActivity-1721213940847-onPaused"},{"name":"ui.photos.ImageActivity-1721213940855-onStopped"},{"name":"ui.photos.ImageActivity-1721213940860-onDestroyed"},{"name":"ui.photos.ImageActivity-1721213940955-onCreated"}]}
--- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
Full: 24579 bytes, write: 24579 bytes, limit: 1048576 bytes, reject: 0 bytes.
log end: 20240717185902

**Comment by FlyJingFish** [comment]
你这代码混淆了吧，你最起码把堆栈信息还原到混淆前的代码，才好排查呀，这样看不出来
