### ISSUE TITLE
手势放大缩小在大屏幕尺寸下不灵敏

### ISSUE THREAD

**Issue by zyizyiz** [FlyJingFish/OpenImage#33]
**描述一下大概怎么回事**
在大屏幕情况下，在手势放大缩小的时候，单手操作困难，当两个触摸点相隔较大的时候才可以有对应的手势显示

**如何复现**
把复现步骤详细说明说下

**错误日志**
把错误日志贴出来

**截图说明**
添加截图最好是 gif 或 视频

**设备信息:**
 - 手机型号: [e.g. 小米]
 - Android版本 [e.g. Android 12]
 - 使用的哪个库及其版本： 最新版

**Comment by FlyJingFish** [comment]
什么样的设备，平板吗

**Comment by zyizyiz** [comment]
https://github.com/user-attachments/assets/fcf0e544-114a-4dcd-beb2-2ba5f976ca93

两个触点之间距离太小的话，会当作滑动响应了

**Comment by FlyJingFish** [comment]
嗯，已初步定位问题，我找个平板测试下该如何处理这个阈值，近期会更新版本，更新后我会在此通知一下
