### ISSUE TITLE
打开大图后，中间的进度条有时不消失

### ISSUE THREAD

**Issue by kingboup** [FlyJingFish/OpenImage#34]
**描述一下大概怎么回事**
<img width="686" alt="Clipboard_Screenshot_1723100498" src="https://github.com/user-attachments/assets/a30c570e-e4eb-4001-92f2-0f6897cac4a8">

<img width="808" alt="Clipboard_Screenshot_1723100628" src="https://github.com/user-attachments/assets/f9b73a3c-d34f-4888-89bf-efff2c40ee03">

<img width="719" alt="Clipboard_Screenshot_1723100515" src="https://github.com/user-attachments/assets/398fb0e7-d774-435e-b6b5-bf383d1a0b75">

**截图说明**
<img width="350" alt="Clipboard_Screenshot_1723100420" src="https://github.com/user-attachments/assets/9d340441-8098-4a38-8c0d-d9fac3820ebb">

**设备信息:**
 - 手机型号: [e.g. 小米]
 - Android版本 [e.g. Android 12]
 - 使用的哪个库及其版本 'io.github.FlyJingFish.OpenImage:OpenImageGlideLib:2.2.5'

**Comment by FlyJingFish** [comment]
这种情况在真机上会这样吗，看你这情况好像是在模拟器上

**Comment by kingboup** [comment]
是的，真机上

![Uploading Clipboard_Screenshot_1723166568.png…]()

**Comment by FlyJingFish** [comment]
你提供一个复现的录屏视频，我这边复现不了

**Comment by FlyJingFish** [comment]
另外你有没有自定义加载图片的fragment？

**Comment by gavinXian** [comment]
请问下，打开的图片是签名笔迹的图片，背景是透明的，笔迹颜色是黑色的，然后显示大图的时候背景颜色也是暗黑了，导致颜色重叠，有办法设置背景色为白色吗？这样才能看清签名笔迹

**Comment by FlyJingFish** [comment]
先关闭这个issues，如有疑问可再开新的

**Comment by Mysqi** [comment]
使用'io.github.FlyJingFish.OpenImage:OpenImageGlideLib:2.3.6',版本也出现了。
目前的处理方案：
继承ImageFragment后，在loadImageFinish回调中设置 loadingView.setImageDrawable(null);

**Comment by FlyJingFish** [comment]
> 使用'io.github.FlyJingFish.OpenImage:OpenImageGlideLib:2.3.6',版本也出现了。 目前的处理方案： 继承ImageFragment后，在loadImageFinish回调中设置 loadingView.setImageDrawable(null);

这样治标不治本，我试试更新下版本
