### ISSUE TITLE
大图显示背景色是否可以修改

### ISSUE THREAD

**Issue by gavinXian** [FlyJingFish/OpenImage#35]
请问下，打开的图片是签名笔迹的图片，背景是透明的，笔迹颜色是黑色的，然后显示大图的时候背景颜色也是暗黑了，导致颜色重叠，有办法设置背景色为白色吗？这样才能看清签名笔迹

**Comment by FlyJingFish** [comment]
[看Wiki文档](https://github.com/FlyJingFish/OpenImage/wiki)
