### ISSUE TITLE
问题与建议

### ISSUE THREAD

**Issue by joevess** [FlyJingFish/OpenImage#4]
[问题：使用.setNoneClickView()时仍会出现：关于查看大图后父Activity的返回动画被修改的问题](https://github.com/FlyJingFish/OpenImage/issues/2)
建议：针对第三方的类似轮播图的控件，无法设置setClickViewPager情况提供支持，或支持其他通用setClickView

**Comment by FlyJingFish** [comment]
1、你所提到的问题最新版本（1.8.1）中已解决
2、你所提到的建议，之前早有 demo [ViewPagerDemoActivity](https://github.com/FlyJingFish/OpenImage/blob/master/app/src/main/java/com/flyjingfish/openimage/activity/ViewPagerDemoActivity.java) 已经针对三方轮播图的做了示范，你可以研究此 demo 来对你的三方轮播图进行对接（只要你的三方轮播图是ViewPager或ViewPager2来实现的一般来说没问题的，前提是你需要对三方库足够了解才能进行对接，再一个三方的轮播图过多不可能对他们做适配的，只能你自己对接了）。此外OpenImage中早就已经存在通用的setClickImageView，你可以获取正在显示的轮播图中的ImageView来传入其中

**Comment by joevess** [comment]
好的，谢谢耐心解答
