### ISSUE TITLE
[Feat] coil版适配coil3

### ISSUE THREAD

**Issue by klxiaoniu** [FlyJingFish/OpenImage#41]
**详细说明功能**
coil已发布3.0版本，包名有所改变，现有2.x版本可与3.0共存。建议发布一个基于coil3的版本，开发者基于项目中已有的coil版本自行选择，避免以下问题：
- 引入的3.0版gif支持在OpenImage不生效（io.coil-kt.coil3:coil-gif:3.0.3）
- 引用OpenImage库后导致项目中多版本共存产生自动import错误。

升级指南：https://coil-kt.github.io/coil/upgrading_to_coil3/

**截图说明**
![image](https://github.com/user-attachments/assets/bb97b769-e55b-472c-b776-1b8dc1fc5ad5)

**Comment by FlyJingFish** [comment]
新版本已提供支持 coil3
另外，gif图不生效并不是你描述的原因，如果还不会，可以查看demo中的 MyApplication 中的配置

**Comment by klxiaoniu** [comment]
> [最新版本](https://github.com/FlyJingFish/OpenImage/releases/tag/v2.3.5)已提供支持 coil3 另外，gif图不生效并不是你描述的原因，如果使用最新版仍然没有gif效果，可以查看demo中的 MyApplication 中的配置

非常感谢！
