### ISSUE TITLE
 initViewPager2()(OpenImageActivity.java:357)出现脚标越界问题

### ISSUE THREAD

**Issue by Zeng-Ke** [FlyJingFish/OpenImage#43]
**描述一下大概怎么回事**
bugly记录到多个异常。

**如何复现**
把复现步骤详细说明说下

**错误日志**

java.lang.RuntimeException:Unable to start activity ComponentInfo{com.yixinli.counselor/com.flyjingfish.openimagelib.StandardOpenImageActivity}: java.lang.IllegalArgumentException: Offscreen page limit must be OFFSCREEN_PAGE_LIMIT_DEFAULT or a number > 0
2
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4788)
3
......
4
Caused by:
5
java.lang.IllegalArgumentException:Offscreen page limit must be OFFSCREEN_PAGE_LIMIT_DEFAULT or a number > 0
6
androidx.viewpager2.widget.ViewPager2.void setOffscreenPageLimit(int)(ViewPager2.java:830)
7
com.flyjingfish.openimagelib.OpenImageActivity.void initViewPager2()(OpenImageActivity.java:357)
8
com.flyjingfish.openimagelib.OpenImageActivity.void onCreate(android.os.Bundle)(OpenImageActivity.java:133)
9
android.app.Activity.performCreate(Activity.java:8592)
10
android.app.Activity.performCreate(Activity.java:8565)
11
android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
12
android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4756)
13
android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:5006)
14
android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:123)
15
android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
16
android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
17
android.app.ActivityThread$H.handleMessage(ActivityThread.java:3082)
18
android.os.Handler.dispatchMessage(Handler.java:117)
19
android.os.Looper.loopOnce(Looper.java:205)
20
android.os.Looper.loop(Looper.java:293)
21
android.app.ActivityThread.loopProcess(ActivityThread.java:9986)
22
android.app.ActivityThread.main(ActivityThread.java:9975)
23
java.lang.reflect.Method.invoke(Native Method)
24
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
25
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

**截图说明**
添加截图最好是 gif 或 视频

**设备信息:**
 - 手机型号: [e.g. 小米]
 - Android版本 [e.g. Android 12]
 - 使用的哪个库及其版本 [e.g. OpenImageGlideLib:1.8.8]

**Comment by FlyJingFish** [comment]
升级至最新版
