### ISSUE TITLE
coloros 13 点击下载提示没有权限

### ISSUE THREAD

**Issue by sceneren** [FlyJingFish/OpenImage#7]
能否把权限拦截放出来自己来实现

**Comment by FlyJingFish** [comment]
1、最新版1.9.8应该已经修复此问题
2、另外你提到的权限放出也有了
3、麻烦看下升级版本后是否正常，另外提bug尽量按格式填写，你这信息太少了

**Comment by FlyJingFish** [comment]
烦请验证后给出是否已修复此问题的结果

**Comment by sceneren** [comment]
权限可以使用了
我之前已经自定义了界面,跳过了你的拦截自己处理了...

**Comment by FlyJingFish** [comment]
你这个方案也是可以的，没想到你仔细阅读文档了👍，你那个手机直接用最新版，用我写的权限检查没问题了吗？

**Comment by sceneren** [comment]
没问题的
