### ISSUE TITLE
ActivityExitTransitionCallbacks 内存泄漏

### ISSUE THREAD

**Issue by sceneren** [FlyJingFish/OpenImage#8]
leakcanay监测到退出的时候 ActivityExitTransitionCallbacks.mActivity内存泄漏

**Comment by FlyJingFish** [comment]
哥们，您上次提bug我就跟你说了按格式填写，你这信息量太少了

**Comment by sceneren** [comment]
**描述一下大概怎么回事**
查看大图退出的时候内存泄露

**如何复现**
同上

**错误日志**
![Screenshot_2023-06-06-13-34-21-98_d9957bfeee2ac50a31045c3c0367836e](https://github.com/FlyJingFish/OpenImage/assets/6612998/1a86a951-6d4d-4b3c-94b4-89aa2400cd36)


**截图说明**

**设备信息:**
 - 手机型号: 一加10Pro
 - Android版本 13
 - 使用的哪个库及其版本: 最新版



就一个内存泄露觉得没必要搞这些😂😂😂

**Comment by sceneren** [comment]
![Screenshot_2023-06-06-13-47-34-11_d9957bfeee2ac50a31045c3c0367836e](https://github.com/FlyJingFish/OpenImage/assets/6612998/65d7a002-1876-4aef-bf8f-7e2a444a64ec)

**Comment by sceneren** [comment]
![Uploading Screenshot_2023-06-06-13-48-47-74_d9957bfeee2ac50a31045c3c0367836e.jpg…]()

**Comment by sceneren** [comment]
![Screenshot_2023-06-06-13-48-47-74_d9957bfeee2ac50a31045c3c0367836e](https://github.com/FlyJingFish/OpenImage/assets/6612998/ed11219d-9421-46b2-a092-28da70140754)

**Comment by FlyJingFish** [comment]
有没必要搞这些，得看情况……

你发的这些内存泄漏出现问题的地方属于Android的源码里的，属于Android 12及其以上才会出现的，所以不是咱这个库里的bug。目前尚且无法解决上述问题，只能等待Google官方解决了。

你可以在Android 11及其以下版本的手机上测试不会出现上述问题

**Comment by FlyJingFish** [comment]
FixAndroid12BugActivity 是一个几乎没有代码的类，以下是全部代码：

```java
package com.flyjingfish.openimagelib;

import androidx.appcompat.app.AppCompatActivity;

public class FixAndroid12BugActivity extends AppCompatActivity {
    @Override
    protected void onResume() {
        super.onResume();
        finishAfterTransition();
    }
}

```

**Comment by FlyJingFish** [comment]
不用过于担心放心用吧，Android源码里有很多bug，这个不是致命的，这个泄漏的内存最多只是可能比Activity 的onDestroy 稍微晚了一点回收，不一定真的泄漏了

**Comment by klxiaoniu** [comment]
> ![Screenshot_2023-06-06-13-47-34-11_d9957bfeee2ac50a31045c3c0367836e](https://user-images.githubusercontent.com/6612998/243559677-65d7a002-1876-4aef-bf8f-7e2a444a64ec.jpg)

在2.1.6版本遇到一样的泄露了

**Comment by FlyJingFish** [comment]
不用管，兄弟，仔细看看上边说的
