### ISSUE TITLE
可以支持从fragment调用吗？

### ISSUE THREAD

**Issue by SaltedFish-Extreme** [FlyJingFish/OpenImage#9]
我的RecyclerView是在activity->fragment->fragment->adapter中的😂我想从这个adapter调用

**Comment by FlyJingFish** [comment]
跟在哪没关系，该传的参数都传对即可

**Comment by SaltedFish-Extreme** [comment]
@FlyJingFish 哦，我的意思是指可以传一个fragment参数吗？或者直接穿context，activity不好获取😂

**Comment by FlyJingFish** [comment]
Fragment中有获取Activity的方法。context也能直接强转成Activity。方法多的是。Fragment中获取的Activity就是你最外层的那个Activity，这属于基础知识……😓在Fragment中有两个方法getActivity  requireactivity  都可以拿到

**Comment by SaltedFish-Extreme** [comment]
这样啊，好吧，不好意思麻烦了😂

**Comment by FlyJingFish** [comment]
[已新增，可以直接使用最新版本即可](https://github.com/FlyJingFish/OpenImage/issues/12)

**Comment by SaltedFish-Extreme** [comment]
好的，麻烦了😁
